apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: booking-postgres-data
  labels:
    app: booking-postgres
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 100Mi
