apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-postgres
  labels:
    app: car-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: car-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: car-postgres
    spec:
      containers:
        - name: car-postgres
          image: postgres:15
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_DB
              value: Car_Rental_Car_Database
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: car-postgres-data
