apiVersion: v1
kind: Service
metadata:
  name: chat-service
  labels:
    app: chat-service
spec:
  type: ClusterIP
  ports:
    - port: 8087
      targetPort: 8087
      name: http
  selector:
    app: chat-service
