apiVersion: v1
kind: Service
metadata:
  name: feedback-postgres
  labels:
    app: feedback-postgres
spec:
  type: ClusterIP
  ports:
    - port: 5437
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: feedback-postgres
