apiVersion: v1
kind: Service
metadata:
  name: payment-postgres
  labels:
    app: payment-postgres
spec:
  type: ClusterIP
  ports:
    - port: 5436
      targetPort: 5432
      name: postgres
  selector:
    app: payment-postgres
