apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payment-postgres-data
  labels:
    app: payment-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard
