apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    io.kompose.service: user-service
spec:
  selector:
    io.kompose.service: user-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  type: ClusterIP
