spring.application.name=
server.port=

spring.mail.host=
spring.mail.port=
spring.mail.username=
spring.mail.password=
spring.mail.protocol=
spring.mail.properties.mail.smtp.auth=
spring.mail.properties.mail.smtp.starttls.enable=
spring.mail.properties.mail.smtp.starttls.required=
spring.mail.default-encoding=

spring.kafka.bootstrap-servers=
spring.kafka.consumer.key-deserializer=
spring.kafka.consumer.value-deserializer=
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=
spring.kafka.consumer.properties.spring.json.trusted.packages=
spring.kafka.consumer.properties.spring.json.use.type.headers=
spring.kafka.consumer.auto-offset-reset=
spring.kafka.consumer.enable-auto-commit=

eureka.client.service-url.defaultZone=
eureka.client.register-with-eureka=
eureka.client.fetch-registry=
eureka.instance.prefer-ip-address=
