spring.application.name=
server.port=

eureka.client.service-url.defaultZone=
eureka.client.register-with-eureka=
eureka.client.fetch-registry=
eureka.instance.prefer-ip-address=
eureka.client.healthcheck.enabled=

spring.cloud.gateway.server.webflux.discovery.locator.enabled=
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=

logging.level.org.springframework.cloud.gateway=
logging.level.reactor.netty.http.client=

