spring.application.name=
server.port=

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=
spring.jpa.hibernate.ddl-auto=
spring.jpa.show-sql=

jwt.secret=

spring.kafka.bootstrap-servers=
spring.kafka.consumer.group-id=
spring.kafka.consumer.auto-offset-reset=
spring.kafka.consumer.key-deserializer=
spring.kafka.consumer.value-deserializer=
spring.kafka.consumer.properties.spring.json.trusted.packages=

spring.elasticsearch.uris=
spring.elasticsearch.connection-timeout=
spring.elasticsearch.socket-timeout=
spring.elasticsearch.connection-request-timeout=

eureka.client.service-url.defaultZone=
eureka.client.register-with-eureka=
eureka.client.fetch-registry=
eureka.instance.prefer-ip-address=
