spring.application.name=
server.port=

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=
spring.jpa.hibernate.ddl-auto=
spring.jpa.show-sql=

jwt.secret=
jwt.expiration=
jwt.refresh-expiration=

spring.data.redis.host=
spring.data.redis.port=

spring.mail.host=
spring.mail.port=
spring.mail.username=
spring.mail.password=
spring.mail.protocol=
spring.mail.properties.mail.smtp.auth=
spring.mail.properties.mail.smtp.starttls.enable=
spring.mail.properties.mail.smtp.starttls.required=
spring.mail.default-encoding=

spring.rabbitmq.host=
spring.rabbitmq.port=
spring.rabbitmq.username=
spring.rabbitmq.password=

spring.elasticsearch.uris=
spring.elasticsearch.connection-timeout=
spring.elasticsearch.socket-timeout=
spring.elasticsearch.connection-request-timeout=

eureka.client.service-url.defaultZone=
eureka.client.register-with-eureka=
eureka.client.fetch-registry=
eureka.instance.prefer-ip-address=

