spring.application.name=
server.port=

jwt.secret=

spring.data.mongodb.uri=

spring.rabbitmq.host=
spring.rabbitmq.port=
spring.rabbitmq.username=
spring.rabbitmq.password=

spring.elasticsearch.uris=
spring.elasticsearch.connection-timeout=
spring.elasticsearch.socket-timeout=
spring.elasticsearch.connection-request-timeout=

eureka.client.service-url.defaultZone=
eureka.client.register-with-eureka=
eureka.client.fetch-registry=
eureka.instance.prefer-ip-address=

